DROP TABLE IF EXISTS  entries;

CREATE TABLE entries (
  id INT AUTO_INCREMENT,
   CONVERSION_TYPE VARCHAR(250) NOT NULL,
  FROM_MEASUREMENT VARCHAR(250) NOT NULL,
  TO_MEASUREMENT VARCHAR(250) NOT NULL,
  ASKED_VALUE VARCHAR(250) NOT NULL,
  WRITTEN_VALUE VARCHAR(250) NOT NULL,
  RESULT VARCHAR(250) NOT NULL
);

INSERT INTO entries (CONVERSION_TYPE, FROM_MEASUREMENT, TO_MEASUREMENT, ASKED_VALUE,WRITTEN_VALUE,RESULT ) VALUES
  ('TEMPERATURE', 'RANKINE', 'KELVIN', '1.0','2.0','INCORRECT');
